server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Venkat5357/cloud-configuration-repo
  application:
    name: cloud-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




